name: Rebase from Upstream
on:
  # Schedule to run daily at 03:00 UTC (midnight BRT)
  schedule:
    - cron: '0 3 * * *'  # Corrected cron syntax
  # Allow manual trigger in the Actions tab
  workflow_dispatch:
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # fetch full history so rebase works
          token: ${{ secrets.GITHUB_TOKEN }}  # Add this for push access
      
      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Add and fetch upstream
        run: |
          git remote add upstream https://github.com/zbirenbaum/copilot.lua.git
          git fetch upstream
      
      - name: Rebase onto upstream/master
        run: |
          git checkout master
          git rebase upstream/master
      
      - name: Push rebased master
        run: |
          git push --force-with-lease origin master
